applications:
    app:
        source:
            root: "/"

        type: "php:8.3"

        runtime:
            extensions:
                - apcu
                - blackfire
                - ctype
                - iconv
                - mbstring
                - pdo_pgsql
                - sodium
                - xsl

        variables:
            php:
                opcache.preload: config/preload.php

        build:
            flavor: none

        relationships:
            database: "database:postgresql"

        mounts:
            "/var/cache":
                source: local
                source_path: var/cache

        hooks:
            build: |
                set -x -e
                curl -fs https://get.symfony.com/cloud/configurator | bash
                NODE_VERSION=22 symfony-build

            deploy: |
                set -x -e
                symfony-deploy

        web:
            locations:
                "/":
                    root: "public"
                    expires: 1h
                    passthru: "/index.php"

services:
    database:
        type: "postgresql:16"

routes:
    "https://{default}/":
        type: upstream
        upstream: "app:http"
        primary: true

    "http://{default}/":
        type: redirect
        to: "https://{default}/"
